import { defineConfig } from 'vitest/config';

export default defineConfig({
  test: {
    globals: true,
    include: [
      'src/__tests__/api-football-canonical-adapter.test.ts',
      'src/__tests__/canonical-provider-domain.test.ts',
      'src/__tests__/pipeline-live-input.test.ts',
      'src/__tests__/provider-fixture-mapping-service.test.ts',
      'src/__tests__/provider-fusion-odds-promotion.test.ts',
      'src/__tests__/provider-fusion-odds-shadow.test.ts',
      'src/__tests__/provider-fusion-pipeline-read.test.ts',
      'src/__tests__/provider-fusion-stats-events-promotion.test.ts',
      'src/__tests__/provider-fusion-snapshot.test.ts',
      'src/__tests__/sportmonks-api.test.ts',
      'src/__tests__/sportmonks-canonical-adapter.test.ts',
      'src/__tests__/sportmonks-normalize.test.ts',
      'src/__tests__/sportmonks-provider-fallback.test.ts',
      'src/__tests__/the-odds-api.test.ts',
      'src/__tests__/the-odds-api-canonical-adapter.test.ts',
      'src/__tests__/provider-fixture-mappings.repo.test.ts',
      'src/__tests__/provider-fixture-samples.repo.test.ts',
      'src/__tests__/provider-request-ledger.repo.test.ts',
    ],
    testTimeout: 10_000,
    hookTimeout: 20_000,
    pool: 'forks',
    coverage: {
      provider: 'v8',
      all: true,
      clean: true,
      reportsDirectory: 'coverage/provider-fusion',
      reporter: ['text', 'json-summary'],
      include: [
        'src/lib/canonical/api-football-adapter.ts',
        'src/lib/canonical/api-football-odds-adapter.ts',
        'src/lib/canonical/provider-domain.ts',
        'src/lib/canonical/sportmonks-adapter.ts',
        'src/lib/canonical/the-odds-api-adapter.ts',
        'src/lib/pipeline-live-input.ts',
        'src/lib/provider-fixture-mapping-service.ts',
        'src/lib/provider-fusion-odds-promotion.ts',
        'src/lib/provider-fusion-odds-shadow.ts',
        'src/lib/provider-fusion-pipeline-read.ts',
        'src/lib/provider-fusion-stats-events-promotion.ts',
        'src/lib/provider-fusion-snapshot.ts',
        'src/lib/sportmonks-api.ts',
        'src/lib/sportmonks-normalize.ts',
        'src/lib/sportmonks-provider-fallback.ts',
        'src/lib/the-odds-api.ts',
        'src/repos/provider-fixture-mappings.repo.ts',
        'src/repos/provider-fixture-samples.repo.ts',
        'src/repos/provider-request-ledger.repo.ts',
      ],
    },
  },
});
