export const strategicSourcePolicyBase = {
  officialDomains: [
    'fifa.com',
    'uefa.com',
    'the-afc.com',
    'cafonline.com',
    'concacaf.com',
    'ofcfootball.com',
    'premierleague.com',
    'laliga.com',
    'seriea.it',
    'bundesliga.com',
    'ligue1.com',
    'efl.com',
    'mlssoccer.com',
  ],
  majorNewsDomains: [
    'reuters.com',
    'apnews.com',
    'bbc.com',
    'bbc.co.uk',
    'theguardian.com',
    'aljazeera.com',
    'espn.com',
    'skysports.com',
    'theathletic.com',
    'nbcsports.com',
    'foxsports.com',
    'goal.com',
  ],
  statsReferenceDomains: [
    'fbref.com',
    'soccerway.com',
    'transfermarkt.com',
    'transfermarkt.co.uk',
    'sofascore.com',
    'flashscore.com',
    'fotmob.com',
    'whoscored.com',
    'worldfootball.net',
  ],
  rejectedDomainPatterns: [
    'reddit.com',
    'x.com',
    'twitter.com',
    'facebook.com',
    'instagram.com',
    'youtube.com',
    'youtu.be',
    'tiktok.com',
    'telegram.me',
    'blogspot.',
    'wordpress.',
    'medium.com',
    'substack.com',
    'tipster',
    'betting',
    'oddschecker',
    'freesupertips',
    'forum',
  ],
  aggregatorPatterns: [
    'score',
    'sport',
    'news',
  ],
} as const;
